services:
  - type: web
    name: recipe-app-backend
    env: node
    plan: free
    buildCommand: ""
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_atlas_url
      - key: PORT
        value: 3000
